# Generated by Django 4.1.3 on 2022-11-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('login', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=18)),
                ('birth', models.DateField()),
                ('tg', models.CharField(blank=True, max_length=24)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
